version: '3'

services:
  nodejs:
    build: 
      context: .
      dockerfile: Dockerfile
    image: juangaray22/conversao-temperatura:v1
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "8080:8080"